baseURL: "https://lorenzopalloni.github.io"
languageCode: en-us
title: Lorenzo Palloni
theme: "PaperMod"

enableEmoji: true
pygmentsUseClasses: true  # ?

minify:
    disableXML: true
    minifyOutput: true  # ?

params:
    author: Lorenzo Palloni
    description: "Lorenzo Palloni's personal website."
    env: production  # to enable google analytics, opengraph, twitter-cards and schema.

    defaultTheme: auto
    ShowShareButtons: true  # bottom share buttons in single posts
    ShareButtons: false
    ShowReadingTime: true
    ShowCodeCopyButtons: true
    comments: true
    # images: ["me_thinking.jpeg"]  # ?
    # enableInlineShortcodes: true
    # ShowToc: true
    # disableThemeToggle: true
    # disableSpecial1stPost: true
    # displayFullLangName: true
    # ShowPostNavLinks: true
    # ShowBreadCrumbs: true

    profileMode:
        enabled: true
        title: Lorenzo Palloni
        subtitle: >
            Data Scientist
        # imageUrl: "me_thinking_cropped.jpeg"
        # imageTitle: Me thinking
        # imageWidth: 150
        # imageHeight: 150
        buttons:
            # - name: Bio
            #   url: bio/
            #   weight: 1
            # - name: Works
            #   url: works/
            #   weight: 2
            # - name: Posts
            #   url: posts/
            #   weight: 3

    socialIcons:
        - name: github
          url: "https://github.com/lorenzopalloni"
        - name: linkedin
          url: "https://www.linkedin.com/in/lorenzo-palloni-758b76145"

    # homeInfoParams:
    #     Title: "Lorenzo Palloni"
    #     Content: >
    #         Welcome to my website! 😊


#     editPost:
#         URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
#         Text: "Suggest Changes" # edit text
#         appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        favicon: "icon-64x64.ico"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

# taxonomies:
#     category: categories
#     tag: tags
#     series: series

# markup:
#     goldmark:
#         renderer:
#             unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

# privacy:
#     vimeo:
#         disabled: false
#         simple: true
#
#     twitter:
#         disabled: false
#         enableDNT: true
#         simple: true
#
#     instagram:
#         disabled: false
#         simple: true
#
#     youtube:
#         disabled: false
#         privacyEnhanced: true
#
# services:
#     instagram:
#         disableInlineCSS: true
#     twitter:
#         disableInlineCSS: true

menu:
    main:
        - name: Bio
          url: bio/
          weight: 1
        # - name: Works
        #   url: works/
        #   weight: 2
        - name: Posts
          url: posts/
          weight: 3
        - name: Résumé
          url: "LorenzoPalloniCV.pdf"
          weight: 4

