# Basic Configuration
baseURL: "https://lorenzopalloni.github.io"
languageCode: en-us
title: Lorenzo Palloni
theme: "PaperMod"

# Features
enableEmoji: true  # Enable Emoji support
pygmentsUseClasses: true  # Use CSS classes for syntax highlighting instead of inline styles

# Minification Settings
minify:
  disableXML: true  # Disable minification for XML files
  minifyOutput: true  # Enable output minification for faster page load

# Site Parameters
params:
  author: Lorenzo Palloni
  description: "Lorenzo Palloni's personal website."
  env: production  # Use 'production' for live sites to enable additional features like analytics

  # Theme Customization
  defaultTheme: auto  # Automatically switch between light and dark mode based on user preference
  ShowShareButtons: true  # Display share buttons at the bottom of single posts
  ShowReadingTime: true  # Show estimated reading time for posts
  ShowCodeCopyButtons: true  # Show 'Copy' button for code blocks
  comments: true  # Enable comments on posts

  # Profile Configuration (Displayed prominently on the home page)
  profileMode:
    enabled: true
    title: Lorenzo Palloni
    subtitle: "[Embedded Machine Learning Engineer](./posts/what-does-an-embedded-ml-engineer-do/)"
    imageUrl: "me_thinking_cropped.jpeg"
    buttons: []
    # Example button configuration:
    # - name: Bio
    #   url: bio/
    #   weight: 1

  # Social Icons (Displayed in the footer or header)
  socialIcons:
    - name: github
      url: "https://github.com/lorenzopalloni"
    - name: linkedin
      url: "https://www.linkedin.com/in/lorenzo-palloni-758b76145"

  # Site Assets
  assets:
    favicon: "icon-64x64.ico"
    # Additional favicon sizes and icons can be specified here

# Menu Configuration
menu:
  main:
    - name: Bio
      url: bio/
      weight: 1
    - name: Posts
      url: posts/
      weight: 3
    - name: Résumé
      url: "LorenzoPalloniCV.pdf"
      weight: 4

# Uncomment and configure the sections below as needed
# editPost:
#   URL: "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
#   Text: "Suggest Changes"
#   appendFilePath: true

# analytics:
#   google:
#     SiteVerificationTag: "Your Google Site Verification Code"

# Privacy settings for various services
# privacy:
#   vimeo:
#     disabled: false
#     simple: true
#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true
